# Generated by Django 4.0 on 2022-12-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_is_expert_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleUsersCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.IntegerField(blank=True, default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.IntegerField(blank=True, default=0)),
                ('c2', models.IntegerField(blank=True, default=0)),
                ('c3', models.IntegerField(blank=True, default=0)),
                ('c4', models.IntegerField(blank=True, default=0)),
                ('c5', models.IntegerField(blank=True, default=0)),
                ('c6', models.IntegerField(blank=True, default=0)),
                ('c7', models.IntegerField(blank=True, default=0)),
                ('c8', models.IntegerField(blank=True, default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customuser')),
            ],
        ),
    ]
